production:
  adapter: postgresql
  encoding: unicode
  database: json_api_bench_production
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: json_api_bench_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: json_api_bench_development
  pool: 5
